const ADD_BOOK = 'ADD_BOOK';
const REMOVE_BOOK = 'REMOVE_BOOK';
const STATUS_CATEGORIES = 'CHECK_STATUS';
const FETCH_BOOKS = 'FETCH_BOOKS';

export {
  ADD_BOOK, REMOVE_BOOK,
  STATUS_CATEGORIES, FETCH_BOOKS,
};
